apiVersion: apps/v1
kind: Deployment

metadata:
  name: learning-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: learning-app

  template:
    metadata:
      labels:
        app: learning-app

    spec:
      containers:
        - name: learning-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: learning-app-config
                  key: NODE_ENV
          
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          readinessProbe:
            httpGet:    
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20