apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: learning-app-pvc

spec:
  accessModes:
    - ReadWriteOnce # Allow the PVC to be mounted as read-write by a single node

  resources:
    requests:
      storage: 1Gi