apiVersion: v1
kind: Service

metadata:
  name: learning-app

spec:
  selector:
    app: learning-app

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000

  type: {{ .Values.service.type }}