replicaCount: 3

image:
  repository: kubernetes-argocd-learning-app
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 3000

ingress:
  host: prod.learning-app.local

env: production