replicaCount: 1

image:
  repository: kubernetes-argocd-learning-app
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true # Habilita el recurso Ingress para esta aplicación
  host: dev.learning-app.local

env: dev