# Deploys your containerized app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment # Nombre del despliegue
  labels:
    app: app # Etiqueta para identificar los recursos relacionados con la aplicación
spec:
  replicas: 2
  selector: # Selector para identificar los pods que pertenecen a este despliegue
    matchLabels:
      app: app
  template: # Plantilla para los pods que se crearán
    metadata: # Metadatos para los pods, incluyendo etiquetas para que el selector pueda identificarlos
      labels:
        app: app # Etiqueta para identificar los pods relacionados con la aplicación
    spec:
      containers: # Definición de los contenedores que se ejecutarán en los pods
        - name: app # Nombre del contenedor
          image: kubernetes-argocd-learning-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
